### ISSUE TITLE
Inquire for source code of this paper

### ISSUE THREAD

**Issue by judydnguyen** [AntigoneRandy/QCB-LACPDA#1]
Dear Authors,

I am interested in your ICML paper "Purifying Quantization-conditioned Backdoors via Layer-wise Activation Correction with Distribution Approximation" but it seems to be that this repo has not been ready yet. May I ask for the code and when should it be released? Thanks!

**Comment by walkeralan123** [comment]
> Dear Authors,
> 
> I am interested in your ICML paper "Purifying Quantization-conditioned Backdoors via Layer-wise Activation Correction with Distribution Approximation" but it seems to be that this repo has not been ready yet. May I ask for the code and when should it be released? Thanks!

Thank you for your interest. It will be released soon, possibly in the next few weeks. Please stay tuned.

**Comment by AntigoneRandy** [comment]
Dear @judydnguyen, thank you very much for your interest. Our code is now publicly available. Feel free to use it!
